# Copyright (c) 2023-2024 iFarbod. All Rights Reserved.
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: CI

on:
  push:
    branches:
      - master
    paths-ignore:
      - "**.md"

jobs:
  macos-build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # run a shallow clone

      - name: Check Clang
        run: ls -la /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk

      - name: Create ZIP package
        run: |
          SDK_PATH="/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk"
          cd "$SDK_PATH"
          zip -r macos_sdk.zip .
          mv macos_sdk.zip $GITHUB_WORKSPACE

      - name: Upload SDK package as artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-sdk-package
          path: $GITHUB_WORKSPACE/macos_sdk.zip
