# Copyright (c) 2023-2024 iFarbod. All Rights Reserved.
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: CI

on:
  push:
    branches:
      - master
    paths-ignore:
      - "**.md"

jobs:
  macos-build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # run a shallow clone

      - name: Check Clang
        run: clang --version
      - name: Build
        run: clang --target=arm64e-apple-darwin -E -dM a.cpp | grep -i ztl | sort
        
