# Copyright (c) 2023-2024 iFarbod. All Rights Reserved.
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: CI

on:
  push:
    branches:
      - master
    paths-ignore:
      - "**.md"

jobs:
  macos-build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # run a shallow clone

      - name: Create ZIP package
        run: |
          ls -la /Applications/Xcode.app/Contents/Developer/Platforms
          SDK_PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk"
          zip -r iPhoneOS_sdk.zip "$SDK_PATH"

      - name: Upload SDK package as artifact
        uses: actions/upload-artifact@v4
        with:
          name: sdk-package
          path: iPhoneOS_sdk.zip
